Отправка на первое ревью
Aleksey-Zhivov/stellar-burger pull request #1
Opened 2024-04-01 10:16 UTC by Aleksey-Zhivov

Реализован функционал в рамках задания для ПР:
настроен роутинг, защищенные маршруты, раскиданы данные из стора по всем компонентам, которым они нужны, реализована процедура регистрации, авторизации и логаута.
Дополнительно выводятся статусы заказа в ЛК пользователя.

2024-04-02 06:08 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/c7TSCIjgT2lLqQ> - иконка должна быть активной, только у активной ссылки.

- Информация о заказе `/profile/orders/:id` не открывается в новой вкладке (даже если пользователь авторизован). Скорее всего, вам нужно поправить компонент `protect-route`.

- <https://disk.yandex.com/i/l_g13tzCzt37yw> - у вас не должен вызываться запрос для получение всех заказов при открытии приложения. Этот запрос должен вызываться только на странице `/feed`, пометил в коде место, которое нужно будет исправить;

- Редьюсеры — это чистые функции, в них не должно быть работы с localStorage и т.п. Для этого есть экшены. Можете там дождаться выполнение запроса) и поставить в куки и localStorage нужные вам данные.

### **Сделает код лучше:**

- <https://disk.yandex.com/i/MwacmI9xTmd79Q> - не сильно критично, но лучше чтобы контент был по центру страницы.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/app/app.tsx
> +      dispatch(fetchFeedsApi());
**Надо исправить:**

Здесь не должно быть вызова `dispatch(fetchFeedsApi());`. Получение списка заказов должно быть только на странице `/feed`;

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/app/app.tsx
> +    if (!isLoading) {
**Можно лучше:**

Лучше это убрать, т.к. `useEffect` будет вызываться только 1 раз, при запуске приложения.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +    console.log(getCookie('accessToken'));
*Можно лучше:**

Лучше удалить все console.log, alert и debugger, которые используются во время отладки.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +    }
**Можно лучше:**

лучше чуток поменять условие, чтобы не делать `else`.

```suggestion
    if (!isAuthenticated) {
      navigate('/login');
    }

    const { bun, ingredients } = items;

    if (!bun) {
      alert('Сначала соберите свой вкуснейший бургер!');

      return;
    }

    const order: string[] = [
      bun._id,
      ...ingredients.map((ingredient) => ingredient._id),
      bun._id
    ];

    dispatch(fetchOrderBurgerApi(order));
```

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +        (s: number, v: TConstructorIngredient) => s + v.price,
**Надо исправить:**

лучше давать осмысленные название переменным в цикле - `acc, ingredient`.

А также, тут можно не указывать дополнительно тип, ts сам подхватит его.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  /** TODO: взять переменные из стора */
**Можно лучше:**

комментарии лучше убрать)

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  );
**Можно лучше:**

здесь допускается использование useMemo, чтобы фильтрация ингредиентов не вызывалась при каждом рендере

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/protected-route/protected-route.tsx
> +};
**Надо исправить:**

У вас мелькают защищённые страницы, при перезагрузке.
Вы должны тут просто дождаться получение пользователя и проверить авторизован он или нет.

Оптимальный пример компонента ProtectRoute:

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

Вам не хватает вот этой проверки, поэтому у вас и мелькают защищённые страницы.

```js
if (!isAuthChecked) {
  return <Preloader />;
}
```

`isAuthChecked` - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет `true` (не зависит от результат, т.к. он будет `true` в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет `false`.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/ui/app-header/app-header.tsx
> +              to={'/login'}
**Надо исправить:**

здесь должна быть ссылка `/profile`. Компонент ProtectRoute сам перенаправит пользователя на страницу логина, если это будет нужно.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/components/ui/order-status/order-status.tsx
> +  }
**Можно лучше:**

Логику лучше писать в другом компоненте `src\components\order-status\order-status.tsx`, а ui компонент использовать чисто для вывода информации.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/pages/constructor-page/constructor-page.tsx
> +  /** TODO: взять переменную из стора */
**Можно лучше:**

лучше убрать комментарии

2024-04-02 06:08 UTC, ArslanMustafin commented on src/pages/feed/feed.tsx
> +    */
Хех, действительно нету, спасибо, сообщу авторам. 🔥

2024-04-02 06:08 UTC, ArslanMustafin commented on src/pages/feed/feed.tsx
> +    <FeedUI orders={orders} handleGetFeeds={() => dispatch(fetchFeedsApi())} />
**Надо исправить:**

`() => dispatch(fetchFeedsApi())` - лучше вынести в отдельную функцию. Иначе у вас будет происходить запрос каждый ререндер компонента. А происходить это будет, потому что каждый раз ссылка на функцию будет новая.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/services/slices/authSlice.ts
> +          : (state.error = '');
**Можно лучше:**

не совсем понял смысл условия, почему бы просто не написать? 

`action.error.message = action.error.message;`

2024-04-02 06:08 UTC, ArslanMustafin commented on src/services/slices/authSlice.ts
> +        localStorage.setItem('refreshToken', action.payload.refreshToken);
**Надо исправить:**

здесь и далее.

Редьюсеры — чистые функции, в них не должно быть работы с localStorage и т.п. Для этого есть экшены. Можете там дождаться выполнение запроса) и поставить в куки и localStorage нужные вам данные.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/services/slices/burgerCunstructorSlice.ts
> +      }
**Надо исправить:**

Редьюсеры — чистые функции, в них не должно быть генерации каких-нибудь айдишников. 

```js
//пример:

    addToConstructor: {
      reducer: (state, { payload }: PayloadAction<TConstructorIngredient>) => {
        if (payload.type === 'bun') {
          state.bun = payload;
        } else {
          state.ingredients.push(payload);
        }
      },
      prepare: (ingredient: TIngredient) => ({
        payload: { ...ingredient, id: uuid() }
      })
    },

```

2024-04-02 06:08 UTC, ArslanMustafin commented on src/services/slices/burgerCunstructorSlice.ts
> +    addIngredients: (state, action) => {
**Надо исправить:**

Здесь и далее.

вам нужно типизировать экшены в редьюсере. Пример показал в комментарии ниже.

2024-04-02 06:08 UTC, ArslanMustafin commented on src/services/slices/ingredientSlice.ts
> +    getIngredients: (state) => {
**Надо исправить:**

Здесь и далее.

вам нужно типизировать экшены в редьюсере.

2024-04-02 07:49 UTC, Aleksey-Zhivov commented on src/components/app/app.tsx
> +      dispatch(fetchFeedsApi());
исправлено, убран диспатч ленты

2024-04-02 07:51 UTC, Aleksey-Zhivov commented on src/components/burger-constructor/burger-constructor.tsx
> +    console.log(getCookie('accessToken'));
удалено:)

2024-04-02 07:54 UTC, Aleksey-Zhivov commented on src/components/burger-constructor/burger-constructor.tsx
> +    }
спасибо за совет, решил воспользоваться им :)

2024-04-02 08:07 UTC, Aleksey-Zhivov commented on src/components/burger-constructor/burger-constructor.tsx
> +        (s: number, v: TConstructorIngredient) => s + v.price,
исправлено
если честно, это функционал из стартер кита, но я согласен, что можно было и поправить

2024-04-02 08:09 UTC, Aleksey-Zhivov commented on src/services/slices/authSlice.ts
> +          : (state.error = '');
действительно, вначале я почему-то думал, что это поможет чистить error, но уже не помню почему:) так как это так не работало, сделал для сброса ошибок специальный экшен

2024-04-02 08:16 UTC, Aleksey-Zhivov commented on src/components/app/app.tsx
> +    if (!isLoading) {
исправил

2024-04-02 08:17 UTC, Aleksey-Zhivov commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  /** TODO: взять переменные из стора */
комментарий удален :)

2024-04-02 08:32 UTC, Aleksey-Zhivov commented on src/components/ui/app-header/app-header.tsx
> +              to={'/login'}
исправлено

2024-04-02 08:33 UTC, Aleksey-Zhivov commented on src/pages/constructor-page/constructor-page.tsx
> +  /** TODO: взять переменную из стора */
исправлено:)

2024-04-02 08:36 UTC, Aleksey-Zhivov commented on src/pages/feed/feed.tsx
> +    */
спасибо :)

2024-04-02 09:37 UTC, Aleksey-Zhivov commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  );
вроде сделал, но получилось по одной мемоизации на каждый тип, выглядит немного громоздко, но работает

2024-04-02 09:52 UTC, Aleksey-Zhivov commented on src/components/ui/order-status/order-status.tsx
> +  }
спасибо, оказалось, что там уже все предсоздано, но есть ошибка:)
в return изначально было text={statusText[**textStyle**]} вместо text={statusText[**status**]}

2024-04-02 09:54 UTC, Aleksey-Zhivov commented on src/pages/feed/feed.tsx
> +    <FeedUI orders={orders} handleGetFeeds={() => dispatch(fetchFeedsApi())} />
исправил, пошел осознавать в чем разница :)

2024-04-02 11:50 UTC, Aleksey-Zhivov commented on src/components/protected-route/protected-route.tsx
> +};
я пытался реализовать этот компонент так, как показано в примере, тем более что такой же пример был в теории, но что-то пошло не так и прелоадер показывался всегда, поэтому я его убрал. 
вроде починилось, но пришлось добавить в условие флаг реквеста данных пользователя

2024-04-02 17:17 UTC, Aleksey-Zhivov commented on src/services/slices/authSlice.ts
> +        localStorage.setItem('refreshToken', action.payload.refreshToken);
было сложно.. попробовал реализовать данный функционал в reducer, но не получилось (надо подумать почему), получилось сделать через unwrap() при хендлсабмите в логин, регистер и логаут, но решил сделать внутри asyncThunk

2024-04-02 17:29 UTC, Aleksey-Zhivov commented on src/services/slices/burgerCunstructorSlice.ts
> +      }
оооо! я совсем забыл про prepare, спасибо!

2024-04-02 19:35 UTC, Aleksey-Zhivov commented on src/services/slices/burgerCunstructorSlice.ts
> +    addIngredients: (state, action) => {
исправлено

2024-04-02 19:36 UTC, Aleksey-Zhivov commented on src/services/slices/ingredientSlice.ts
> +    getIngredients: (state) => {
исправлено

2024-04-02 22:16 UTC, Aleksey-Zhivov commented
правки выполнены

2024-04-03 18:02 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Осталось исправить одно маленькое замечание:**

- Роут `/profile/orders/:id` должен быть доступен, только авторизованным пользователям, т.е. защищён компонентом protect-route. Просто оберните компонент в ProtectRoute.

```js
<Route
  path='/profile/orders/:number'
  element={
    <ProtectedRoute>
      <OrderInfo />
    </ProtectedRoute>
  }
/>
```

2024-04-03 18:02 UTC, ArslanMustafin commented on src/components/ui/app-header/app-header.tsx
> +              currentLocation === '/profile/orders/:number'
**Можно лучше:**

Тут и в похожих местах, используйте `useMatch` из react-router-dom

https://reactrouter.com/en/main/start/overview#active-links

2024-04-03 18:22 UTC, Aleksey-Zhivov commented on src/components/ui/app-header/app-header.tsx
> +              currentLocation === '/profile/orders/:number'
исправлено, спасибо :)

2024-04-03 18:26 UTC, Aleksey-Zhivov commented
Я специально убрал оборачивание модалки с заказом в `<ProtectedRoute>`, так как возвращается проблема с редиректом в профиль. Для наглядности вернул обратно. Решения как переделать `<ProtectedRoute>`, я не придумал и не нашел :(
 Моя логика была такова - тут не нужен защищенный маршрут, так как сторонний пользователь не получит этот путь, так как его можно получить только из профиля (если, конечно, он не в курсе этого пути). Вообще такой функционал довольно распространен и вроде как утечки данных там нет (хоть я и не уверен).

2024-04-03 20:41 UTC, Aleksey-Zhivov commented
UPDATE:
решена проблема с `ProtectedRoute` - изменение пути в компоненте `Navigate` с `'/profile'` на `from`

2024-04-04 04:31 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-04-04 05:50 UTC, merged